### ISSUE TITLE
Setup but It's not able to connect to wireguard

### ISSUE THREAD

**Issue by genieai-vikas** [egor-tensin/setup-wireguard#2]
I created .conf file. Now using that .cong file I am trying to set up wireguard connect in Github.

```
      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: 18.124.82.43:54321
          endpoint_public_key: 9WrjQWqKx0w72RzIsdffjQwjPOpsffRjHMDD4=
          ips: 10.50.0.16/32
          allowed_ips: 0.0.0.0/0, ::/0
          private_key: MMB38wvXwLh0UIU5qjrE6vXwOBQnUSciBgq2xBkG=
          preshared_key: kZJdGX8iZNSTY4eUp2cm21wihUGoOyuJhf56xsBzHf=
```
The step is completed but when I tried to access the URL which can only be accessed when connected to VPN is not accessible.
